name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: create output dir
        run: mkdir output
      - uses: docker://pandoc/core:3.8
        with:
          args: >-
            --standalone
            --output=output/Trabajo_Nutricion.docx
            "Trabajo de Nutricion y alimentacion animal."
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output
